/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeviceTelemetryStateDto } from '../../models/device-telemetry-state-dto';

export interface FindLatestStateByDeviceId$Params {

/**
 * Stable external device id
 */
  deviceId: string;
}

export function findLatestStateByDeviceId(http: HttpClient, rootUrl: string, params: FindLatestStateByDeviceId$Params, context?: HttpContext): Observable<StrictHttpResponse<DeviceTelemetryStateDto>> {
  const rb = new RequestBuilder(rootUrl, findLatestStateByDeviceId.PATH, 'get');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeviceTelemetryStateDto>;
    })
  );
}

findLatestStateByDeviceId.PATH = '/api/v1/device/{deviceId}/state';
