/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeviceCommandRequestDto } from '../../models/device-command-request-dto';
import { DeviceCommandResultDto } from '../../models/device-command-result-dto';

export interface PublishCommand$Params {

/**
 * Stable external device id
 */
  deviceId: string;
      body: DeviceCommandRequestDto
}

export function publishCommand(http: HttpClient, rootUrl: string, params: PublishCommand$Params, context?: HttpContext): Observable<StrictHttpResponse<DeviceCommandResultDto>> {
  const rb = new RequestBuilder(rootUrl, publishCommand.PATH, 'post');
  if (params) {
    rb.path('deviceId', params.deviceId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeviceCommandResultDto>;
    })
  );
}

publishCommand.PATH = '/api/v1/device/{deviceId}/commands';
