/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeviceCapability } from '../models/device-capability';
import { DeviceStatus } from '../models/device-status';
import { DeviceTransport } from '../models/device-transport';
import { DeviceType } from '../models/device-type';

/**
 * Device registry entry exposed by the HomeOps API.
 */
export interface DeviceDto {

  /**
   * Capabilities supported by this device.
   */
  capabilities?: Array<DeviceCapability>;

  /**
   * Creation timestamp.
   */
  createdAt?: string;

  /**
   * Longer free-text description.
   */
  description?: string;

  /**
   * Stable external device id used in API paths and MQTT topics.
   */
  deviceId?: string;

  /**
   * Human-readable device name.
   */
  displayName?: string;

  /**
   * Whether this device is enabled in HomeOps.
   */
  enabled?: boolean;

  /**
   * Last time the device was observed online or reported data.
   */
  lastSeenAt?: string;

  /**
   * Physical or logical location.
   */
  location?: string;

  /**
   * Short functional role of the device.
   */
  role?: string;

  /**
   * Current registry status of the device.
   */
  status?: DeviceStatus;

  /**
   * Primary communication or management transport.
   */
  transport?: DeviceTransport;

  /**
   * General device category.
   */
  type?: DeviceType;

  /**
   * Last update timestamp.
   */
  updatedAt?: string;

  /**
   * Optimistic locking version.
   */
  version?: number;
}
