/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeviceTransport } from './device-transport';

/**
 * Each possible value of `DeviceTransport`
 */
export const DEVICE_TRANSPORT: DeviceTransport[] = [
  'MQTT',
  'HTTP',
  'SSH',
  'DOCKER',
  'MANUAL',
  'WEBSOCKET',
  'OTHER',
  'UNKNOWN'
];