/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum DeviceType {
  SERVER = 'SERVER',
  MICROCONTROLLER = 'MICROCONTROLLER',
  SENSOR = 'SENSOR',
  ACTUATOR = 'ACTUATOR',
  CAMERA = 'CAMERA',
  MINER = 'MINER',
  LAPTOP = 'LAPTOP',
  ROUTER = 'ROUTER',
  OTHER = 'OTHER'
}
