/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JsonNode } from '../models/json-node';
export interface DeviceCommandRequestDto {
  command: string;
  property: string;
  target: string;
  value: JsonNode;
}
