/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum DeviceStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  UNKNOWN = 'UNKNOWN',
  ALERT = 'ALERT',
  ERROR = 'ERROR'
}
