/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeviceType } from './device-type';

/**
 * Each possible value of `DeviceType`
 */
export const DEVICE_TYPE: DeviceType[] = [
  'SERVER',
  'MICROCONTROLLER',
  'SENSOR',
  'ACTUATOR',
  'CAMERA',
  'MINER',
  'LAPTOP',
  'ROUTER',
  'OTHER'
];