/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeviceCreateDto {
  capabilities?: Array<'TEMPERATURE_SENSOR' | 'HUMIDITY_SENSOR' | 'LIGHT_SENSOR' | 'FAN_SWITCH' | 'LIGHT_SWITCH' | 'CAMERA_SNAPSHOT' | 'HASHRATE_MONITORING' | 'TEMPERATURE_MONITORING' | 'CPU_METRICS' | 'MEMORY_METRICS' | 'DISK_METRICS' | 'DOCKER_HOST' | 'MQTT_BROKER' | 'CI_RUNNER' | 'OTHER'>;
  description?: string;
  deviceId: string;
  displayName: string;
  location?: string;
  role?: string;
  transport?: 'MQTT' | 'HTTP' | 'SSH' | 'DOCKER' | 'MANUAL' | 'WEBSOCKET' | 'OTHER' | 'UNKNOWN';
  type: 'SERVER' | 'MICROCONTROLLER' | 'SENSOR' | 'ACTUATOR' | 'CAMERA' | 'MINER' | 'LAPTOP' | 'ROUTER' | 'OTHER';
}
