/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Device registry entry exposed by the HomeOps API.
 */
export interface DeviceDto {

  /**
   * Capabilities supported by this device.
   */
  capabilities?: Array<'TEMPERATURE_SENSOR' | 'HUMIDITY_SENSOR' | 'LIGHT_SENSOR' | 'FAN_SWITCH' | 'LIGHT_SWITCH' | 'CAMERA_SNAPSHOT' | 'HASHRATE_MONITORING' | 'TEMPERATURE_MONITORING' | 'CPU_METRICS' | 'MEMORY_METRICS' | 'DISK_METRICS' | 'DOCKER_HOST' | 'MQTT_BROKER' | 'CI_RUNNER' | 'OTHER'>;

  /**
   * Creation timestamp.
   */
  createdAt?: string;

  /**
   * Longer free-text description.
   */
  description?: string;

  /**
   * Stable external device id used in API paths and MQTT topics.
   */
  deviceId?: string;

  /**
   * Human-readable device name.
   */
  displayName?: string;

  /**
   * Whether this device is enabled in HomeOps.
   */
  enabled?: boolean;

  /**
   * Last time the device was observed online or reported data.
   */
  lastSeenAt?: string;

  /**
   * Physical or logical location.
   */
  location?: string;

  /**
   * Short functional role of the device.
   */
  role?: string;

  /**
   * Current registry status of the device.
   */
  status?: 'ONLINE' | 'OFFLINE' | 'UNKNOWN' | 'ALERT' | 'ERROR';

  /**
   * Primary communication or management transport.
   */
  transport?: 'MQTT' | 'HTTP' | 'SSH' | 'DOCKER' | 'MANUAL' | 'WEBSOCKET' | 'OTHER' | 'UNKNOWN';

  /**
   * General device category.
   */
  type?: 'SERVER' | 'MICROCONTROLLER' | 'SENSOR' | 'ACTUATOR' | 'CAMERA' | 'MINER' | 'LAPTOP' | 'ROUTER' | 'OTHER';

  /**
   * Last update timestamp.
   */
  updatedAt?: string;

  /**
   * Optimistic locking version.
   */
  version?: number;
}
