/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type DeviceType = 'SERVER' | 'MICROCONTROLLER' | 'SENSOR' | 'ACTUATOR' | 'CAMERA' | 'MINER' | 'LAPTOP' | 'ROUTER' | 'OTHER';

