/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum DeviceTransport {
  MQTT = 'MQTT',
  HTTP = 'HTTP',
  SSH = 'SSH',
  DOCKER = 'DOCKER',
  MANUAL = 'MANUAL',
  WEBSOCKET = 'WEBSOCKET',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN'
}
