/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeviceStatus } from './device-status';

/**
 * Each possible value of `DeviceStatus`
 */
export const DEVICE_STATUS: DeviceStatus[] = [
  'ONLINE',
  'OFFLINE',
  'UNKNOWN',
  'ALERT',
  'ERROR'
];