/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { FindByDeviceId$Params as FindByDeviceId$Params } from './fn/device/find-by-device-id';
export { findByDeviceId as findByDeviceId } from './fn/device/find-by-device-id';
export type { Update$Params as Update$Params } from './fn/device/update';
export { update as update } from './fn/device/update';
export type { Delete$Params as Delete$Params } from './fn/device/delete';
export { delete$ as delete$ } from './fn/device/delete';
export type { FindAll$Params as FindAll$Params } from './fn/device/find-all';
export { findAll as findAll } from './fn/device/find-all';
export type { Create$Params as Create$Params } from './fn/device/create';
export { create as create } from './fn/device/create';
export type { GetSystemInfo$Params as GetSystemInfo$Params } from './fn/system-endpoint/get-system-info';
export { getSystemInfo as getSystemInfo } from './fn/system-endpoint/get-system-info';
