/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiErrorResponse } from './models/api-error-response';
export type { DeviceCapability } from './models/device-capability';
export type { DeviceCreateDto } from './models/device-create-dto';
export type { DeviceDto } from './models/device-dto';
export type { DeviceStatus } from './models/device-status';
export type { DeviceTransport } from './models/device-transport';
export type { DeviceType } from './models/device-type';
export type { DeviceUpdateDto } from './models/device-update-dto';
export type { SystemInfoDto } from './models/system-info-dto';
export type { ValidationErrorDto } from './models/validation-error-dto';
